export const WEATHER_CODE_MAP: { [key: number]: string } = {
  0: 'Clear',
  1: 'Clear',
  2: 'Partly Cloudy',
  3: 'Mostly Cloudy',
  45: 'Fog',
  48: 'Fog',
  51: 'Rainy',
  53: 'Rainy',
  55: 'Rainy',
  56: 'Sleet/Hail',
  57: 'Sleet/Hail',
  61: 'Rainy',
  63: 'Rainy',
  65: 'Heavy Rain',
  66: 'Sleet/Hail',
  67: 'Sleet/Hail',
  71: 'Snowy',
  73: 'Snowy',
  75: 'Snowy',
  77: 'Sleet/Hail',
  80: 'Rainy',
  81: 'Heavy Rain',
  82: 'Heavy Rain',
  85: 'Snowy',
  86: 'Snowy',
  95: 'Thunderstorm',
  96: 'Thunderstorm',
  99: 'Thunderstorm',
};

export const WEATHER_IMAGE_MAP: { [key: number]: string } = {
  0: 'assets/sun.png',
  1: 'assets/sun.png',
  2: 'assets/partly-cloudy.png',
  3: 'assets/mostly-cloudy.png',
  45: 'assets/fog.png',
  48: 'assets/fog.png',
  51: 'assets/rain.png',
  53: 'assets/rain.png',
  55: 'assets/rain.png',
  56: 'assets/sleet.png',
  57: 'assets/sleet.png',
  61: 'assets/rain.png',
  63: 'assets/rain.png',
  65: 'assets/heavy-rain.png',
  66: 'assets/sleet.png',
  67: 'assets/sleet.png',
  71: 'assets/snow.png',
  73: 'assets/snow.png',
  75: 'assets/snow.png',
  77: 'assets/sleet.png',
  80: 'assets/rain.png',
  81: 'assets/heavy-rain.png',
  82: 'assets/heavy-rain.png',
  85: 'assets/snow.png',
  86: 'assets/snow.png',
  95: 'assets/thunder.png',
  96: 'assets/thunder.png',
  99: 'assets/thunder.png',
};
